-- Replace solver constraint catalog with business descriptions that match
-- solver_service/solver.py and ConstraintsInput (not design prototype text).

DELETE FROM "luxlait_solver_constraints";

INSERT INTO "luxlait_solver_constraints" (
    "id", "category", "group_name", "title", "description", "metric", "impact",
    "weight", "active", "editable", "sort_order", "created_at", "updated_at"
) VALUES
(
    'lock_plan',
    'HARD',
    'Planning figé',
    'Jours verrouillés',
    'Les affectations déjà acceptées ou verrouillées sont réinjectées telles quelles. Elles occupent la capacité des machines et ne sont pas recalculées.',
    'existing_assignments',
    'Base fixe pour un replanage partiel.',
    NULL,
    true,
    false,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'qual_machine',
    'HARD',
    'Compétences',
    'Qualification par machine',
    'Une variable d''affectation n''existe que si le collaborateur possède une compétence sur la machine (autonome ou en formation).',
    'skills',
    'Impossible d''affecter hors référentiel compétences.',
    NULL,
    true,
    false,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'indispo_jour',
    'HARD',
    'Disponibilité',
    'Indisponibilités jour',
    'Les journées marquées indisponibles pour un employé dans les données d''entrée ne reçoivent aucune affectation travail.',
    'unavailable_days',
    'Aligné congés et absences jour dans l''API de résolution.',
    NULL,
    true,
    false,
    2,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'indispo_shift',
    'HARD',
    'Disponibilité',
    'Indisponibilités créneau',
    'Les couples jour et créneau interdits pour un employé excluent ce créneau pour ce jour.',
    'unavailable_shifts',
    'Permet de bloquer un shift précis sans bloquer toute la journée.',
    NULL,
    true,
    false,
    3,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'shift_machine',
    'HARD',
    'Machines',
    'Créneaux ouverts et fermetures',
    'Si la machine a des créneaux ouverts, le shift choisi doit être compatible. Les fermetures machine par jour ou par créneau interdisent l''affectation sur ces créneaux.',
    'open_time_slots, fermetures',
    'Respect du calendrier machine renseigné en base.',
    NULL,
    true,
    false,
    4,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cov_mandatory',
    'HARD',
    'Machines',
    'Couverture machine obligatoire',
    'Pour une machine en importance MANDATORY, chaque créneau ouvert non fermé doit avoir au moins un opérateur qualifié présent sur ce poste et ce créneau.',
    'importance MANDATORY',
    'Sinon le solveur déclare l''instance infaisable.',
    NULL,
    true,
    false,
    5,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cap_max',
    'HARD',
    'Machines',
    'Plafond par créneau',
    'Sur chaque machine, jour et créneau ouvrable, le nombre de personnes simultanées ne dépasse pas max employés, diminué des personnes déjà verrouillées sur ce créneau.',
    'max_employees',
    'Évite la suroccupation d''un poste.',
    NULL,
    true,
    false,
    6,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'training_partner',
    'HARD',
    'Formation',
    'Formation jamais isolée',
    'Un opérateur en compétence IN_TRAINING sur une machine ne peut pas être seul sur ce machine, jour et créneau : au moins un collègue AUTONOMOUS doit être présent (figé ou choisi par le solveur).',
    'IN_TRAINING / AUTONOMOUS',
    'Garantit un tuteur effectif sur le créneau.',
    NULL,
    true,
    false,
    7,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'min_staff',
    'HARD',
    'Effectifs',
    'Effectif minimum par créneau',
    'Lorsqu''un minimum d''employés est défini pour une machine, un jour et un créneau, la somme des affectations atteint ce plancher si des candidats existent.',
    'machine_shift_min_requirements',
    'Sinon instance rejetée si le plancher est impossible.',
    NULL,
    true,
    false,
    8,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'night_morning',
    'HARD',
    'Repos',
    'Enchaînement nuit puis matin',
    'Lorsque les créneaux nuit et matin sont détectés par leur nom, il est interdit d''enchaîner un service nuit un jour et un service matin le lendemain pour le même employé (y compris parties figées prises en compte).',
    'repos déduit des time_slots',
    'Limite la fatigue liée à ce type de bascule.',
    NULL,
    true,
    false,
    9,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'enforce_slot',
    'HARD',
    'Modèle',
    'Créneau obligatoire si jour travaillé',
    'Si le paramètre enforce time slot when assigned est actif, une journée travaillée se voit attribuer exactement un créneau parmi les créneaux ouvrables.',
    'booléen',
    'Évite une machine sans shift choisi.',
    NULL,
    true,
    false,
    10,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'obj_equity',
    'SOFT',
    'Objectif',
    'Équité charge',
    'Réduit l''écart entre le nombre minimal et maximal de jours travaillés par employé sur la fenêtre (pondération fairness weight).',
    'défaut 1',
    'Lisse la charge entre personnes éligibles.',
    1,
    true,
    true,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'obj_priority',
    'SOFT',
    'Objectif',
    'Machines prioritaires',
    'Maximise la couverture des créneaux ouverts pour les machines en importance PRIORITY lorsque la couverture n''est pas une contrainte dure (pondération priority machine weight).',
    'défaut 50',
    'Favorise les postes marqués prioritaires.',
    50,
    true,
    true,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'obj_stability',
    'SOFT',
    'Objectif',
    'Stabilité plan de référence',
    'Lorsqu''un plan de référence est fourni et que le poids est strictement positif, favorise de conserver la même machine et le même créneau que la référence (pondération stability weight).',
    'défaut 0',
    'Utile au replanage incrémental.',
    0,
    true,
    true,
    2,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'obj_train_bonus',
    'SOFT',
    'Objectif',
    'Affecter les profils formation pure',
    'Bonus pour chaque jour où un employé qui n''a que des compétences en formation est affecté : il doit être placé pour pouvoir être binômé avec un autonome (pondération training bonus weight).',
    'défaut 10',
    'Évite de laisser ces profils sans mission.',
    10,
    true,
    true,
    3,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'obj_poly_a',
    'SOFT',
    'Objectif',
    'Polyvalents sur poste autonome',
    'Bonus lorsqu''un employé à la fois autonome et en formation sur des machines différentes est placé sur une machine où il est autonome ce jour là (pondération polyvalent in autonomous bonus weight).',
    'défaut 7',
    'Priorise le travail productif pour les polyvalents.',
    7,
    true,
    true,
    4,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'obj_poly_f',
    'SOFT',
    'Objectif',
    'Polyvalents sur poste formation',
    'Bonus plus faible lorsque ce même profil polyvalent est placé sur une machine en formation ce jour là (pondération polyvalent in training bonus weight).',
    'défaut 6',
    'Autorise la formation si aucun slot autonome n''est disponible.',
    6,
    true,
    true,
    5,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'obj_extra_pen',
    'SOFT',
    'Objectif',
    'Pénalité sur effectif au delà du minimum',
    'Pénalise chaque personne au delà du minimum requis sur un triplet machine, jour, créneau lorsqu''un minimum est défini (pondération extra coverage penalty weight).',
    'défaut 5',
    'Limite le sur effectif inutile sur un shift.',
    5,
    true,
    true,
    6,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'meta_solver',
    'PREF',
    'Moteur',
    'Temps et précision de résolution',
    'Le solveur CP SAT utilise un temps maximum de calcul et une tolérance d''optimisation relative (quality gap). Ce sont des réglages techniques, pas des règles métier pondérées.',
    'solve_time_limit_seconds, relative_gap_limit',
    'Équilibre qualité de solution et durée d''attente.',
    NULL,
    true,
    false,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
