-- CreateEnum
CREATE TYPE "SolverConstraintCategory" AS ENUM ('HARD', 'SOFT', 'PREF');

-- CreateTable
CREATE TABLE "luxlait_solver_constraints" (
    "id" TEXT NOT NULL,
    "category" "SolverConstraintCategory" NOT NULL,
    "group_name" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "metric" TEXT,
    "impact" TEXT,
    "weight" INTEGER,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "editable" BOOLEAN NOT NULL DEFAULT false,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "luxlait_solver_constraints_pkey" PRIMARY KEY ("id")
);

-- Seed constraints (design handoff; read only display)
INSERT INTO "luxlait_solver_constraints" (
    "id", "category", "group_name", "title", "description", "metric", "impact",
    "weight", "active", "editable", "sort_order", "created_at", "updated_at"
) VALUES
(
    'rest11',
    'HARD',
    'Légal',
    'Repos quotidien minimum',
    '11 h consécutives entre la fin d''un shift et le début du suivant.',
    '11 h',
    'Bloque toute combinaison N vers M le lendemain.',
    NULL,
    true,
    false,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'rest35',
    'HARD',
    'Légal',
    'Repos hebdomadaire',
    '35 h consécutives par semaine glissante.',
    '35 h',
    'Empêche 7 jours de travail consécutifs.',
    NULL,
    true,
    false,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'maxh48',
    'HARD',
    'Légal',
    'Plafond hebdomadaire',
    'Maximum 48 h sur une semaine, 44 h en moyenne sur 4 semaines.',
    '48 h max',
    'Stoppe les heures supplémentaires excessives.',
    NULL,
    true,
    false,
    2,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'qualified',
    'HARD',
    'Sécurité',
    'Habilitation machine',
    'Un opérateur ne peut être affecté qu''à une machine dans son référentiel de compétences.',
    '100 %',
    'Filtre obligatoire : non négociable.',
    NULL,
    true,
    false,
    3,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'mincover',
    'HARD',
    'Production',
    'Couverture minimale',
    'Chaque machine MANDATORY doit avoir au moins 1 opérateur par shift ouvert.',
    '≥ 1 op.',
    'Le solveur échoue si la couverture est impossible.',
    NULL,
    true,
    false,
    4,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'noabsence',
    'HARD',
    'RH',
    'Respect des absences',
    'Congés validés et arrêts maladie ne peuvent jamais être planifiés.',
    '—',
    'Croisement automatique avec le module Congés.',
    NULL,
    true,
    false,
    5,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'targetcap',
    'SOFT',
    'Production',
    'Capacité cible par machine',
    'Vise le maxEmp configuré sur chaque machine, sans dépassement.',
    '≤ maxEmp',
    'Favorise une couverture pleine sans sur staffing.',
    90,
    true,
    true,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'fairshift',
    'SOFT',
    'RH',
    'Équité de rotation M/A/N',
    'Répartit équitablement les shifts sur le mois pour chaque opérateur.',
    '± 2 shifts',
    'Évite que le même employé prenne trop de nuits.',
    75,
    true,
    true,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'consecdays',
    'SOFT',
    'RH',
    'Limiter les jours consécutifs',
    'Préfère ne pas dépasser 5 jours travaillés d''affilée.',
    '≤ 5 j',
    'Diminue la fatigue et l''absentéisme.',
    80,
    true,
    true,
    2,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'rotcoherent',
    'SOFT',
    'RH',
    'Cohérence de rotation',
    'Garde un opérateur sur le même shift plusieurs jours d''affilée.',
    '≥ 3 j',
    'Favorise la régularité du rythme circadien.',
    65,
    true,
    true,
    3,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'samemachine',
    'SOFT',
    'Production',
    'Continuité machine',
    'Privilégie la même machine que la veille pour limiter les changements.',
    '70 %',
    'Réduit les temps d''adaptation.',
    70,
    true,
    true,
    4,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'crosstrain',
    'SOFT',
    'Production',
    'Polyvalence',
    'Sollicite occasionnellement les compétences secondaires.',
    '1×/sem',
    'Maintient la polyvalence des opérateurs.',
    35,
    true,
    true,
    5,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'backup',
    'SOFT',
    'Production',
    'Préférer les titulaires',
    'Place les opérateurs marqués BACKUP en dernier recours.',
    '—',
    'Garde une réserve mobilisable en cas d''imprévu.',
    50,
    true,
    true,
    6,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'weekend',
    'SOFT',
    'RH',
    'Rotation des week ends',
    'Distribue les week ends ouvrés équitablement.',
    '1/3',
    'Inactif tant que les ouvertures week end ne sont pas activées.',
    60,
    false,
    true,
    7,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'prefnight',
    'PREF',
    'Préférences',
    'Préférences de shift',
    'Tient compte des shifts préférés ou évités saisis par les opérateurs.',
    '42 actives',
    'Améliore la satisfaction sans bloquer le solveur.',
    40,
    true,
    true,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'binome',
    'PREF',
    'Préférences',
    'Binômes',
    'Tente de regrouper les opérateurs qui travaillent bien ensemble.',
    '12 paires',
    'Effet faible : utilisé en départage.',
    30,
    true,
    true,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'avoidpair',
    'PREF',
    'Préférences',
    'Incompatibilités',
    'Évite de planifier deux opérateurs en conflit sur le même shift.',
    '3 paires',
    'Important pour le climat d''équipe.',
    55,
    true,
    true,
    2,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
